keys:
  - &oxa F90FFD6D585C2BA1F13DE8A97571654CF88E31C2

  - &invar age157zcs4687hmsd834xhvt66apf6v93ss3tt2l23x72lhtvpl69ggqeejgky
  - &blacksteel age1l9qly5vlx20uzrqvq8qygvcrtff64mgvqchet5uvs989upy5lugq4krj2c
  - &lithium age13h9q4p7evpfjg94j0uxt2jccldexjcf4ay2ylys8f79lclykwchqc7tppq

creation_rules:
  - path_regex: secrets/ssh\.yaml$
    key_groups:
      - age:
          - *invar
          - *blacksteel
        pgp:
          - *oxa

  - path_regex: /invar/secret\.yaml$
    key_groups:
      - age:
          - *invar
        pgp:
          - *oxa

  - path_regex: /blacksteel/secret\.yaml$
    key_groups:
      - age:
          - *blacksteel
        pgp:
          - *oxa

  - path_regex: /lithium/secret\.yaml$
    key_groups:
      - age:
          - *lithium
        pgp:
          - *oxa
