keys:
  - &oxa age1p9ulxm09pwv2cx8m2wwg87s8m05r4yp4ph2rh7p9tavtjye8zd2sh3nnzr
  - &invar age157zcs4687hmsd834xhvt66apf6v93ss3tt2l23x72lhtvpl69ggqeejgky
  - &blacksteel age1l9qly5vlx20uzrqvq8qygvcrtff64mgvqchet5uvs989upy5lugq4krj2c
  - &silver age14z6h0yqmuymga4kxtvc78tmpyjdt7vh72c6awml2dfxjzxch5cqqt374sn
  - &lithium age17qk6m9lnqefs03rs9sv3jruvynjwhnash63k7g629vskk3jngvuqanhfq3

creation_rules:
  - path_regex: secrets/ssh\.yaml$
    key_groups:
      - age:
        - *oxa
        - *invar
        - *blacksteel
        - *silver

  - path_regex: secrets/silver\.yaml$
    key_groups:
      - age:
        - *oxa
        - *silver

  - path_regex: secrets/user\.yaml$
    key_groups:
      - age:
        - *oxa
        - *invar
        - *blacksteel
