[colors]
src.manual = "94d8b2be62657e96488038b0e547e3009ed87d40"
fetch.url = "https://gist.githubusercontent.com/lilydjwg/fdeaf79e921c2f413f44b6f613f6ad53/raw/$ver/colors.py"

[rime_latex]
src.git = "https://github.com/shenlebantongying/rime_latex"
fetch.github = "shenlebantongying/rime_latex"
