[btrfs_map_physical]
# https://github.com/osandov/osandov-linux/blob/master/scripts/btrfs_map_physical.c
src.webpage = "https://api.github.com/repos/osandov/osandov-linux/commits?per_page=1&path=scripts/btrfs_map_physical.c"
src.regex = '"sha"\s*:\s*"(\w+)"'
fetch.url = "https://raw.githubusercontent.com/osandov/osandov-linux/$ver/scripts/btrfs_map_physical.c"

[colors]
src.manual = "94d8b2be62657e96488038b0e547e3009ed87d40"
fetch.url = "https://gist.githubusercontent.com/lilydjwg/fdeaf79e921c2f413f44b6f613f6ad53/raw/$ver/colors.py"

[double-entry-generator]
src.github = "deb-sig/double-entry-generator"
fetch.github = "deb-sig/double-entry-generator"
passthru = { vendorHash = "sha256-yA4ax81rWHTfXj0+8ds4OweUickHtR8QZsgJyulW2j4=" }

[rawmv]
src.github_tag = "oxalica/rawmv"
fetch.github = "oxalica/rawmv"
passthru = { cargoHash = "sha256-sEpvRgvxcH7qnUZ5S3khXdJucmhZ8tl/tIVfpQxV56Y=" }

[rime_latex]
src.git = "https://github.com/shenlebantongying/rime_latex"
fetch.github = "shenlebantongying/rime_latex"

[sway-systemd]
src.github = "alebastr/sway-systemd"
fetch.github = "alebastr/sway-systemd"

# Workaround: https://github.com/swaywm/swaylock/issues/204
[sway-unwrapped]
src.manual = "1.8-rc2"
fetch.github = "swaywm/sway"

# FIXME: https://github.com/NixOS/nixpkgs/pull/180816
[swaylock-effects]
src.github_tag = "jirutka/swaylock-effects"
fetch.github = "jirutka/swaylock-effects"

[tree-sitter-nix]
src.git = "https://github.com/oxalica/tree-sitter-nix"
fetch.github = "oxalica/tree-sitter-nix"
