[colors]
src.manual = "94d8b2be62657e96488038b0e547e3009ed87d40"
fetch.url = "https://gist.githubusercontent.com/lilydjwg/fdeaf79e921c2f413f44b6f613f6ad53/raw/$ver/colors.py"

[double-entry-generator]
src.github = "deb-sig/double-entry-generator"
fetch.github = "deb-sig/double-entry-generator"
passthru = { vendorHash = "sha256-Xedva9oGteOnv3rP4Wo3sOHIPyuy2TYwkZV2BAuxY4M=" }

[rime_latex]
src.git = "https://github.com/shenlebantongying/rime_latex"
fetch.github = "shenlebantongying/rime_latex"

[sway-git-unwrapped]
# FIXME: Latest sway breaks alacritty.
# src.git = "https://github.com/swaywm/sway"
src.manual = "20ffe545bab3fe518d8d1be00949943f7d39cfe0"
fetch.github = "swaywm/sway"

[wlroots-git]
src.git = "https://gitlab.freedesktop.org/wlroots/wlroots.git"
fetch.git = "https://gitlab.freedesktop.org/wlroots/wlroots.git"
