[btrfs_map_physical]
# https://github.com/osandov/osandov-linux/blob/master/scripts/btrfs_map_physical.c
src.webpage = "https://api.github.com/repos/osandov/osandov-linux/commits?per_page=1&path=scripts/btrfs_map_physical.c"
src.regex = '"sha"\s*:\s*"(\w+)"'
fetch.url = "https://raw.githubusercontent.com/osandov/osandov-linux/$ver/scripts/btrfs_map_physical.c"

[double-entry-generator]
src.github = "deb-sig/double-entry-generator"
fetch.github = "deb-sig/double-entry-generator"
passthru = { vendorHash = "sha256-yA4ax81rWHTfXj0+8ds4OweUickHtR8QZsgJyulW2j4=" }

[rawmv]
src.github_tag = "oxalica/rawmv"
fetch.github = "oxalica/rawmv"
passthru = { cargoHash = "sha256-sEpvRgvxcH7qnUZ5S3khXdJucmhZ8tl/tIVfpQxV56Y=" }

[rime_latex]
src.git = "https://github.com/shenlebantongying/rime_latex"
fetch.github = "shenlebantongying/rime_latex"

[sway-unwrapped]
src.git = "https://github.com/swaywm/sway"
fetch.github = "swaywm/sway"

[tree-sitter-bash]
src.git = "https://github.com/tree-sitter/tree-sitter-bash"
fetch.github = "tree-sitter/tree-sitter-bash"

[tree-sitter-nix]
src.git = "https://github.com/oxalica/tree-sitter-nix"
fetch.github = "oxalica/tree-sitter-nix"

[wlroots]
# FIXME: https://github.com/NixOS/nixpkgs/pull/191247
src.manual = "1266f7424f711a3e67477b4aa5192b3c4285c7f4"
# src.git = "https://gitlab.freedesktop.org/wlroots/wlroots"
fetch.git = "https://gitlab.freedesktop.org/wlroots/wlroots"
