[colors]
src.manual = "94d8b2be62657e96488038b0e547e3009ed87d40"
fetch.url = "https://gist.githubusercontent.com/lilydjwg/fdeaf79e921c2f413f44b6f613f6ad53/raw/$ver/colors.py"

[double-entry-generator]
src.github = "deb-sig/double-entry-generator"
fetch.github = "deb-sig/double-entry-generator"
passthru = { vendorHash = "sha256-Xedva9oGteOnv3rP4Wo3sOHIPyuy2TYwkZV2BAuxY4M=" }

[rawmv]
src.github_tag = "oxalica/rawmv"
fetch.github = "oxalica/rawmv"
passthru = { cargoHash = "sha256-sEpvRgvxcH7qnUZ5S3khXdJucmhZ8tl/tIVfpQxV56Y=" }

[rime_latex]
src.git = "https://github.com/shenlebantongying/rime_latex"
fetch.github = "shenlebantongying/rime_latex"

[sway-systemd]
src.github = "alebastr/sway-systemd"
fetch.github = "alebastr/sway-systemd"

# Workaround: https://github.com/swaywm/swaylock/issues/204
[sway-unwrapped]
src.manual = "1.8-rc2"
fetch.github = "swaywm/sway"

# FIXME: https://github.com/NixOS/nixpkgs/pull/180816
[swaylock-effects]
src.github_tag = "jirutka/swaylock-effects"
fetch.github = "jirutka/swaylock-effects"
