# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  colors = {
    pname = "colors";
    version = "94d8b2be62657e96488038b0e547e3009ed87d40";
    src = fetchurl {
      url = "https://gist.githubusercontent.com/lilydjwg/fdeaf79e921c2f413f44b6f613f6ad53/raw/94d8b2be62657e96488038b0e547e3009ed87d40/colors.py";
      sha256 = "sha256-l/RTPZp2v7Y4ffJRT5Fy5Z3TDB4dvWfE7wqMbquXdJA=";
    };
  };
  double-entry-generator = {
    pname = "double-entry-generator";
    version = "v2.1.1";
    src = fetchFromGitHub ({
      owner = "deb-sig";
      repo = "double-entry-generator";
      rev = "v2.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-jE94JOxFwIxDkgedGgIAm1lhSwARPnn7tuii2uWIX5E=";
    });
    vendorHash = "sha256-Xedva9oGteOnv3rP4Wo3sOHIPyuy2TYwkZV2BAuxY4M=";
  };
  rawmv = {
    pname = "rawmv";
    version = "v0.2.0";
    src = fetchFromGitHub ({
      owner = "oxalica";
      repo = "rawmv";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-cH6NahMzifs5OOSE0nBY4kDr+xPtqcOuVghP/g5JTsc=";
    });
    cargoHash = "sha256-sEpvRgvxcH7qnUZ5S3khXdJucmhZ8tl/tIVfpQxV56Y=";
  };
  rime_latex = {
    pname = "rime_latex";
    version = "f4aa38a152418b1c8b8ffa9cc3f9bfa0772d4f85";
    src = fetchFromGitHub ({
      owner = "shenlebantongying";
      repo = "rime_latex";
      rev = "f4aa38a152418b1c8b8ffa9cc3f9bfa0772d4f85";
      fetchSubmodules = false;
      sha256 = "sha256-hVLS9ZMfHnXuqeYHJOF55TEAoikpqcVTW5iYe+yFTtw=";
    });
    date = "2023-03-18";
  };
  sway-git-unwrapped = {
    pname = "sway-git-unwrapped";
    version = "01b0c11394b88fea2ec8ac691e30504f1e0800f5";
    src = fetchFromGitHub ({
      owner = "swaywm";
      repo = "sway";
      rev = "01b0c11394b88fea2ec8ac691e30504f1e0800f5";
      fetchSubmodules = false;
      sha256 = "sha256-M+81OjLWFWiG1HT+KElU81Akpxl4YAPEuTctq6Yzr/g=";
    });
    date = "2023-05-11";
  };
  wlroots-git = {
    pname = "wlroots-git";
    version = "10dd41669492f7582c26bd3989536a66278df75d";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wlroots/wlroots.git";
      rev = "10dd41669492f7582c26bd3989536a66278df75d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-lYmvTWMNcD/1cU7x2CHjLtCtivsO2xz4E87YcPZg24s=";
    };
    date = "2023-05-12";
  };
}
