# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  btrfs_map_physical = {
    pname = "btrfs_map_physical";
    version = "49aec6b85d8457fa25b5d8f6c2afb3dd4592401a";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/osandov/osandov-linux/49aec6b85d8457fa25b5d8f6c2afb3dd4592401a/scripts/btrfs_map_physical.c";
      sha256 = "sha256-KyAIWrSaUJEfpFh7R3u/VYYaC8fQxoCTWb6jlayMufw=";
    };
  };
  double-entry-generator = {
    pname = "double-entry-generator";
    version = "v1.5.2";
    src = fetchFromGitHub ({
      owner = "deb-sig";
      repo = "double-entry-generator";
      rev = "v1.5.2";
      fetchSubmodules = false;
      sha256 = "sha256-RMtXy37DfzFgJSQXntGCRAKe4V3P/6eHoPuwyNmwvN4=";
    });
    vendorHash = "sha256-yA4ax81rWHTfXj0+8ds4OweUickHtR8QZsgJyulW2j4=";
  };
  lsp-inlayhints-nvim = {
    pname = "lsp-inlayhints-nvim";
    version = "9bcd6fe25417b7808fe039ab63d4224f2071d24a";
    src = fetchFromGitHub ({
      owner = "lvimuser";
      repo = "lsp-inlayhints.nvim";
      rev = "9bcd6fe25417b7808fe039ab63d4224f2071d24a";
      fetchSubmodules = false;
      sha256 = "sha256-DyZHs9dYuxOcfjmum5wiAucapSbj/MbqrqBqvGlNirY=";
    });
  };
  rawmv = {
    pname = "rawmv";
    version = "v0.2.0";
    src = fetchFromGitHub ({
      owner = "oxalica";
      repo = "rawmv";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-cH6NahMzifs5OOSE0nBY4kDr+xPtqcOuVghP/g5JTsc=";
    });
    cargoHash = "sha256-sEpvRgvxcH7qnUZ5S3khXdJucmhZ8tl/tIVfpQxV56Y=";
  };
  rime_latex = {
    pname = "rime_latex";
    version = "d484bf6f8d4e4ccdb06c691fa4feeefd1fe58d1c";
    src = fetchFromGitHub ({
      owner = "shenlebantongying";
      repo = "rime_latex";
      rev = "d484bf6f8d4e4ccdb06c691fa4feeefd1fe58d1c";
      fetchSubmodules = false;
      sha256 = "sha256-8k6CCFlXaNKejs6+jusMD4W94IsMZGclL7vFcUy/h+Y=";
    });
  };
  sway-unwrapped = {
    pname = "sway-unwrapped";
    version = "cffb006feba52c318e66f73c3463032fa76782dc";
    src = fetchFromGitHub ({
      owner = "swaywm";
      repo = "sway";
      rev = "cffb006feba52c318e66f73c3463032fa76782dc";
      fetchSubmodules = false;
      sha256 = "sha256-J7HSPnIgxIhVszpE8geptlDsmiZM3KY1nd66xUH+YJk=";
    });
  };
  tree-sitter-bash = {
    pname = "tree-sitter-bash";
    version = "275effdfc0edce774acf7d481f9ea195c6c403cd";
    src = fetchFromGitHub ({
      owner = "tree-sitter";
      repo = "tree-sitter-bash";
      rev = "275effdfc0edce774acf7d481f9ea195c6c403cd";
      fetchSubmodules = false;
      sha256 = "sha256-+XJ6ivsp0q08KWhwEQnAYpU88/gggf6or6oxga5k0ZE=";
    });
  };
  tree-sitter-nix = {
    pname = "tree-sitter-nix";
    version = "add8eb3050a0974c1854df419c192fa4f359bcb0";
    src = fetchFromGitHub ({
      owner = "oxalica";
      repo = "tree-sitter-nix";
      rev = "add8eb3050a0974c1854df419c192fa4f359bcb0";
      fetchSubmodules = false;
      sha256 = "sha256-x2Kq7t0p5AOKIHtEUHMIC6emZNoF9GE2FdKbjEfUp0E=";
    });
  };
  wlroots = {
    pname = "wlroots";
    version = "1266f7424f711a3e67477b4aa5192b3c4285c7f4";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wlroots/wlroots";
      rev = "1266f7424f711a3e67477b4aa5192b3c4285c7f4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-biwaJioxu30Wx7Ek2QUaBBlQSYyl5H4NntHs2uXkWpE=";
    };
  };
}
