# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  colors = {
    pname = "colors";
    version = "94d8b2be62657e96488038b0e547e3009ed87d40";
    src = fetchurl {
      url = "https://gist.githubusercontent.com/lilydjwg/fdeaf79e921c2f413f44b6f613f6ad53/raw/94d8b2be62657e96488038b0e547e3009ed87d40/colors.py";
      sha256 = "sha256-l/RTPZp2v7Y4ffJRT5Fy5Z3TDB4dvWfE7wqMbquXdJA=";
    };
  };
  double-entry-generator = {
    pname = "double-entry-generator";
    version = "v2.3.0";
    src = fetchFromGitHub {
      owner = "deb-sig";
      repo = "double-entry-generator";
      rev = "v2.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-kCyNDLNtsi4qZM8rJwxCGaKvCe4uZUa/RajqiLrmsFM=";
    };
    vendorHash = "sha256-Xedva9oGteOnv3rP4Wo3sOHIPyuy2TYwkZV2BAuxY4M=";
  };
  rime_latex = {
    pname = "rime_latex";
    version = "fb32dc50c19b3913023199ceaae22168cd5a7db7";
    src = fetchFromGitHub {
      owner = "shenlebantongying";
      repo = "rime_latex";
      rev = "fb32dc50c19b3913023199ceaae22168cd5a7db7";
      fetchSubmodules = false;
      sha256 = "sha256-ZSnfkHc0yyXZTVZBjPI8mcjR9CRyKy8qpQFww2VF3QI=";
    };
    date = "2023-06-02";
  };
  sway-git-unwrapped = {
    pname = "sway-git-unwrapped";
    version = "20ffe545bab3fe518d8d1be00949943f7d39cfe0";
    src = fetchFromGitHub {
      owner = "swaywm";
      repo = "sway";
      rev = "20ffe545bab3fe518d8d1be00949943f7d39cfe0";
      fetchSubmodules = false;
      sha256 = "sha256-2plFvH3747PWHRF8il2FipRG79eXxgzTRpy4A24YHGY=";
    };
    date = "2023-06-27";
  };
  wlroots-git = {
    pname = "wlroots-git";
    version = "c68c9f1685e41082679abdf3ae181a21d0e0fc9a";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wlroots/wlroots.git";
      rev = "c68c9f1685e41082679abdf3ae181a21d0e0fc9a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-LlEAVgvAY8s+GJwp//5Ew6Axcb66Xo5qWf3QqYzuGUc=";
    };
    date = "2023-06-27";
  };
}
